"""GC console: workforce, access control, visitors, records, admin

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-02 11:59:03.467342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gc_notification_rules',
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('when_label', sa.String(length=120), nullable=False),
    sa.Column('audience', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_notification_rules_event'), 'gc_notification_rules', ['event'], unique=True)
    op.create_table('gc_projects',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('badge', sa.String(length=8), nullable=False),
    sa.Column('meta', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_projects_code'), 'gc_projects', ['code'], unique=True)
    op.create_table('gc_reference_lists',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_reference_lists_name'), 'gc_reference_lists', ['name'], unique=True)
    op.create_table('gc_role_permissions',
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'capability', name='uq_gc_role_permission')
    )
    op.create_index(op.f('ix_gc_role_permissions_capability'), 'gc_role_permissions', ['capability'], unique=False)
    op.create_index(op.f('ix_gc_role_permissions_role'), 'gc_role_permissions', ['role'], unique=False)
    op.create_table('gc_access_events',
    sa.Column('occurred_label', sa.String(length=32), nullable=False),
    sa.Column('person', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('is_visitor', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_access_events_person'), 'gc_access_events', ['person'], unique=False)
    op.create_index(op.f('ix_gc_access_events_project_id'), 'gc_access_events', ['project_id'], unique=False)
    op.create_table('gc_access_thresholds',
    sa.Column('key_label', sa.String(length=200), nullable=False),
    sa.Column('value_label', sa.String(length=64), nullable=False),
    sa.Column('sub_label', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_access_thresholds_project_id'), 'gc_access_thresholds', ['project_id'], unique=False)
    op.create_table('gc_alerts',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=False),
    sa.Column('badge', sa.String(length=16), nullable=False),
    sa.Column('colour', sa.String(length=16), nullable=False),
    sa.Column('target_screen', sa.String(length=32), nullable=False),
    sa.Column('snoozed_until', sa.String(length=32), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_alerts_kind'), 'gc_alerts', ['kind'], unique=False)
    op.create_index(op.f('ix_gc_alerts_project_id'), 'gc_alerts', ['project_id'], unique=False)
    op.create_table('gc_audit_entries',
    sa.Column('occurred_label', sa.String(length=64), nullable=False),
    sa.Column('who', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('obj', sa.String(length=200), nullable=False),
    sa.Column('value_before', sa.String(length=200), nullable=False),
    sa.Column('value_after', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_audit_entries_action'), 'gc_audit_entries', ['action'], unique=False)
    op.create_index(op.f('ix_gc_audit_entries_project_id'), 'gc_audit_entries', ['project_id'], unique=False)
    op.create_table('gc_companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trade', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('insurance_expiry', sa.String(length=32), nullable=False),
    sa.Column('flag', sa.String(length=64), nullable=False),
    sa.Column('on_register', sa.Integer(), nullable=False),
    sa.Column('on_site', sa.Integer(), nullable=False),
    sa.Column('contract_ref', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_companies_name'), 'gc_companies', ['name'], unique=False)
    op.create_index(op.f('ix_gc_companies_project_id'), 'gc_companies', ['project_id'], unique=False)
    op.create_table('gc_dashboard_tiles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_dashboard_tiles_project_id'), 'gc_dashboard_tiles', ['project_id'], unique=False)
    op.create_table('gc_devices',
    sa.Column('device_ref', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('zone_label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('link', sa.String(length=64), nullable=False),
    sa.Column('buffered_events', sa.Integer(), nullable=False),
    sa.Column('last_sync', sa.String(length=32), nullable=False),
    sa.Column('factor', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_devices_device_ref'), 'gc_devices', ['device_ref'], unique=False)
    op.create_index(op.f('ix_gc_devices_project_id'), 'gc_devices', ['project_id'], unique=False)
    op.create_table('gc_induction_sessions',
    sa.Column('session_ref', sa.String(length=32), nullable=False),
    sa.Column('when_label', sa.String(length=64), nullable=False),
    sa.Column('where_label', sa.String(length=200), nullable=False),
    sa.Column('run_by', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_induction_sessions_project_id'), 'gc_induction_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_induction_sessions_session_ref'), 'gc_induction_sessions', ['session_ref'], unique=False)
    op.create_table('gc_notification_channels',
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['gc_notification_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'channel', name='uq_gc_notification_channel')
    )
    op.create_index(op.f('ix_gc_notification_channels_rule_id'), 'gc_notification_channels', ['rule_id'], unique=False)
    op.create_table('gc_reference_values',
    sa.Column('list_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['gc_reference_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_reference_values_list_id'), 'gc_reference_values', ['list_id'], unique=False)
    op.create_table('gc_report_schedules',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cadence', sa.String(length=120), nullable=False),
    sa.Column('formats', sa.String(length=64), nullable=False),
    sa.Column('recipients', sa.String(length=200), nullable=False),
    sa.Column('last_sent', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_report_schedules_project_id'), 'gc_report_schedules', ['project_id'], unique=False)
    op.create_table('gc_visit_requests',
    sa.Column('visitor_name', sa.String(length=200), nullable=False),
    sa.Column('visitor_kind', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('zones_requested', sa.String(length=200), nullable=False),
    sa.Column('window_label', sa.String(length=64), nullable=False),
    sa.Column('age_label', sa.String(length=32), nullable=False),
    sa.Column('host_is_me', sa.Boolean(), nullable=False),
    sa.Column('host_name', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('decision_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_visit_requests_project_id'), 'gc_visit_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_visit_requests_visitor_name'), 'gc_visit_requests', ['visitor_name'], unique=False)
    op.create_table('gc_visitor_policy',
    sa.Column('policy_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sub_label', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('value_label', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_visitor_policy_policy_key'), 'gc_visitor_policy', ['policy_key'], unique=False)
    op.create_index(op.f('ix_gc_visitor_policy_project_id'), 'gc_visitor_policy', ['project_id'], unique=False)
    op.create_table('gc_visitor_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_incident', sa.String(length=200), nullable=False),
    sa.Column('status_label', sa.String(length=120), nullable=False),
    sa.Column('colour', sa.String(length=16), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_visitor_profiles_name'), 'gc_visitor_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_gc_visitor_profiles_project_id'), 'gc_visitor_profiles', ['project_id'], unique=False)
    op.create_table('gc_zones',
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('zone_ref', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('factor', sa.String(length=8), nullable=False),
    sa.Column('capacity', sa.String(length=16), nullable=False),
    sa.Column('escort_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['gc_zones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_zones_parent_id'), 'gc_zones', ['parent_id'], unique=False)
    op.create_index(op.f('ix_gc_zones_project_id'), 'gc_zones', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_zones_zone_ref'), 'gc_zones', ['zone_ref'], unique=False)
    op.create_table('gc_contractor_accounts',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('last_seen', sa.String(length=32), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['gc_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_contractor_accounts_company_id'), 'gc_contractor_accounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_gc_contractor_accounts_project_id'), 'gc_contractor_accounts', ['project_id'], unique=False)
    op.create_table('gc_induction_attendance',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('worker_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('status_label', sa.String(length=120), nullable=False),
    sa.Column('status_colour', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['gc_induction_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_induction_attendance_project_id'), 'gc_induction_attendance', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_induction_attendance_session_id'), 'gc_induction_attendance', ['session_id'], unique=False)
    op.create_table('gc_plan_shapes',
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('colour', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['gc_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_plan_shapes_level'), 'gc_plan_shapes', ['level'], unique=False)
    op.create_index(op.f('ix_gc_plan_shapes_project_id'), 'gc_plan_shapes', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_plan_shapes_zone_id'), 'gc_plan_shapes', ['zone_id'], unique=False)
    op.create_table('gc_report_runs',
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('ran_at_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['gc_report_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_report_runs_project_id'), 'gc_report_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_report_runs_schedule_id'), 'gc_report_runs', ['schedule_id'], unique=False)
    op.create_table('gc_visits',
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('visitor_name', sa.String(length=200), nullable=False),
    sa.Column('visitor_kind', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=120), nullable=False),
    sa.Column('zones_granted', sa.String(length=200), nullable=False),
    sa.Column('window_label', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('last_event_label', sa.String(length=64), nullable=False),
    sa.Column('visit_date', sa.String(length=32), nullable=False),
    sa.Column('escort', sa.String(length=200), nullable=False),
    sa.Column('credential', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('close_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['gc_visit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_visits_project_id'), 'gc_visits', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_visits_request_id'), 'gc_visits', ['request_id'], unique=False)
    op.create_index(op.f('ix_gc_visits_visitor_name'), 'gc_visits', ['visitor_name'], unique=False)
    op.create_table('gc_workers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('worker_ref', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('job_role', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('zones_permitted', sa.String(length=200), nullable=False),
    sa.Column('on_site', sa.Integer(), nullable=False),
    sa.Column('last_event', sa.String(length=32), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.String(length=32), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.Column('telephone', sa.String(length=32), nullable=False),
    sa.Column('address_local', sa.String(length=255), nullable=False),
    sa.Column('address_home', sa.String(length=255), nullable=False),
    sa.Column('direct_employer', sa.String(length=200), nullable=False),
    sa.Column('induction_date', sa.String(length=32), nullable=False),
    sa.Column('next_of_kin', sa.String(length=200), nullable=False),
    sa.Column('rfid_card', sa.String(length=200), nullable=False),
    sa.Column('face_template', sa.String(length=200), nullable=False),
    sa.Column('second_factor', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['gc_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_workers_company_id'), 'gc_workers', ['company_id'], unique=False)
    op.create_index(op.f('ix_gc_workers_name'), 'gc_workers', ['name'], unique=False)
    op.create_index(op.f('ix_gc_workers_project_id'), 'gc_workers', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_workers_worker_ref'), 'gc_workers', ['worker_ref'], unique=False)
    op.create_table('gc_zone_criteria',
    sa.Column('zone_id', sa.String(length=36), nullable=False),
    sa.Column('requirement', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['gc_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_zone_criteria_project_id'), 'gc_zone_criteria', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_zone_criteria_zone_id'), 'gc_zone_criteria', ['zone_id'], unique=False)
    op.create_table('gc_zone_requirements',
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('zone_name', sa.String(length=200), nullable=False),
    sa.Column('requirement', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['gc_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'zone_name', 'requirement', name='uq_gc_zone_req')
    )
    op.create_index(op.f('ix_gc_zone_requirements_project_id'), 'gc_zone_requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_zone_requirements_zone_id'), 'gc_zone_requirements', ['zone_id'], unique=False)
    op.create_table('gc_blocks',
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('worker_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=False),
    sa.Column('when_label', sa.String(length=32), nullable=False),
    sa.Column('route_back', sa.String(length=200), nullable=False),
    sa.Column('colour', sa.String(length=16), nullable=False),
    sa.Column('lifted', sa.Boolean(), nullable=False),
    sa.Column('lifted_by', sa.String(length=120), nullable=False),
    sa.Column('lifted_reason', sa.String(length=400), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['gc_workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_blocks_project_id'), 'gc_blocks', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_blocks_worker_id'), 'gc_blocks', ['worker_id'], unique=False)
    op.create_index(op.f('ix_gc_blocks_worker_name'), 'gc_blocks', ['worker_name'], unique=False)
    op.create_table('gc_document_submissions',
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=120), nullable=False),
    sa.Column('doc_number', sa.String(length=64), nullable=False),
    sa.Column('expiry', sa.String(length=32), nullable=False),
    sa.Column('issuer', sa.String(length=120), nullable=False),
    sa.Column('submitted', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('decision_reason', sa.String(length=500), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=False),
    sa.Column('decided_at', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['gc_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['gc_workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_document_submissions_company_id'), 'gc_document_submissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_gc_document_submissions_decision'), 'gc_document_submissions', ['decision'], unique=False)
    op.create_index(op.f('ix_gc_document_submissions_project_id'), 'gc_document_submissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_document_submissions_worker_id'), 'gc_document_submissions', ['worker_id'], unique=False)
    op.create_table('gc_report_rows',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('on_register', sa.Integer(), nullable=False),
    sa.Column('on_site', sa.Integer(), nullable=False),
    sa.Column('attended', sa.String(length=16), nullable=False),
    sa.Column('expiring', sa.String(length=16), nullable=False),
    sa.Column('blocked', sa.String(length=16), nullable=False),
    sa.Column('first_in', sa.String(length=16), nullable=False),
    sa.Column('last_out', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['gc_report_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_report_rows_project_id'), 'gc_report_rows', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_report_rows_run_id'), 'gc_report_rows', ['run_id'], unique=False)
    op.create_table('gc_training_records',
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('course', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expiry', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['gc_workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_training_records_project_id'), 'gc_training_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_training_records_worker_id'), 'gc_training_records', ['worker_id'], unique=False)
    op.create_table('gc_violations',
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_label', sa.String(length=32), nullable=False),
    sa.Column('worker_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.Column('colour', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['gc_workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_violations_project_id'), 'gc_violations', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_violations_worker_id'), 'gc_violations', ['worker_id'], unique=False)
    op.create_index(op.f('ix_gc_violations_worker_name'), 'gc_violations', ['worker_name'], unique=False)
    op.create_table('gc_visit_events',
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('when_label', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['gc_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_visit_events_project_id'), 'gc_visit_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_visit_events_visit_id'), 'gc_visit_events', ['visit_id'], unique=False)
    op.create_table('gc_visit_facts',
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['gc_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_visit_facts_project_id'), 'gc_visit_facts', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_visit_facts_visit_id'), 'gc_visit_facts', ['visit_id'], unique=False)
    op.create_table('gc_worker_documents',
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=120), nullable=False),
    sa.Column('doc_number', sa.String(length=64), nullable=False),
    sa.Column('expiry', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['gc_workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_worker_documents_project_id'), 'gc_worker_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_worker_documents_worker_id'), 'gc_worker_documents', ['worker_id'], unique=False)
    op.create_table('gc_submission_fields',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['gc_document_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_submission_fields_project_id'), 'gc_submission_fields', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_submission_fields_submission_id'), 'gc_submission_fields', ['submission_id'], unique=False)
    op.create_table('gc_submission_flags',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['gc_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['gc_document_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_submission_flags_project_id'), 'gc_submission_flags', ['project_id'], unique=False)
    op.create_index(op.f('ix_gc_submission_flags_submission_id'), 'gc_submission_flags', ['submission_id'], unique=False)
    # server_default backfills the rows that already exist; the model default takes
    # over for new rows.
    op.add_column(
        'users', sa.Column('full_name', sa.String(length=120), nullable=False, server_default='')
    )
    op.add_column(
        'users',
        sa.Column('role', sa.String(length=32), nullable=False, server_default='GC user'),
    )
    op.add_column('users', sa.Column('company_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_at')
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'role')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_gc_submission_flags_submission_id'), table_name='gc_submission_flags')
    op.drop_index(op.f('ix_gc_submission_flags_project_id'), table_name='gc_submission_flags')
    op.drop_table('gc_submission_flags')
    op.drop_index(op.f('ix_gc_submission_fields_submission_id'), table_name='gc_submission_fields')
    op.drop_index(op.f('ix_gc_submission_fields_project_id'), table_name='gc_submission_fields')
    op.drop_table('gc_submission_fields')
    op.drop_index(op.f('ix_gc_worker_documents_worker_id'), table_name='gc_worker_documents')
    op.drop_index(op.f('ix_gc_worker_documents_project_id'), table_name='gc_worker_documents')
    op.drop_table('gc_worker_documents')
    op.drop_index(op.f('ix_gc_visit_facts_visit_id'), table_name='gc_visit_facts')
    op.drop_index(op.f('ix_gc_visit_facts_project_id'), table_name='gc_visit_facts')
    op.drop_table('gc_visit_facts')
    op.drop_index(op.f('ix_gc_visit_events_visit_id'), table_name='gc_visit_events')
    op.drop_index(op.f('ix_gc_visit_events_project_id'), table_name='gc_visit_events')
    op.drop_table('gc_visit_events')
    op.drop_index(op.f('ix_gc_violations_worker_name'), table_name='gc_violations')
    op.drop_index(op.f('ix_gc_violations_worker_id'), table_name='gc_violations')
    op.drop_index(op.f('ix_gc_violations_project_id'), table_name='gc_violations')
    op.drop_table('gc_violations')
    op.drop_index(op.f('ix_gc_training_records_worker_id'), table_name='gc_training_records')
    op.drop_index(op.f('ix_gc_training_records_project_id'), table_name='gc_training_records')
    op.drop_table('gc_training_records')
    op.drop_index(op.f('ix_gc_report_rows_run_id'), table_name='gc_report_rows')
    op.drop_index(op.f('ix_gc_report_rows_project_id'), table_name='gc_report_rows')
    op.drop_table('gc_report_rows')
    op.drop_index(op.f('ix_gc_document_submissions_worker_id'), table_name='gc_document_submissions')
    op.drop_index(op.f('ix_gc_document_submissions_project_id'), table_name='gc_document_submissions')
    op.drop_index(op.f('ix_gc_document_submissions_decision'), table_name='gc_document_submissions')
    op.drop_index(op.f('ix_gc_document_submissions_company_id'), table_name='gc_document_submissions')
    op.drop_table('gc_document_submissions')
    op.drop_index(op.f('ix_gc_blocks_worker_name'), table_name='gc_blocks')
    op.drop_index(op.f('ix_gc_blocks_worker_id'), table_name='gc_blocks')
    op.drop_index(op.f('ix_gc_blocks_project_id'), table_name='gc_blocks')
    op.drop_table('gc_blocks')
    op.drop_index(op.f('ix_gc_zone_requirements_zone_id'), table_name='gc_zone_requirements')
    op.drop_index(op.f('ix_gc_zone_requirements_project_id'), table_name='gc_zone_requirements')
    op.drop_table('gc_zone_requirements')
    op.drop_index(op.f('ix_gc_zone_criteria_zone_id'), table_name='gc_zone_criteria')
    op.drop_index(op.f('ix_gc_zone_criteria_project_id'), table_name='gc_zone_criteria')
    op.drop_table('gc_zone_criteria')
    op.drop_index(op.f('ix_gc_workers_worker_ref'), table_name='gc_workers')
    op.drop_index(op.f('ix_gc_workers_project_id'), table_name='gc_workers')
    op.drop_index(op.f('ix_gc_workers_name'), table_name='gc_workers')
    op.drop_index(op.f('ix_gc_workers_company_id'), table_name='gc_workers')
    op.drop_table('gc_workers')
    op.drop_index(op.f('ix_gc_visits_visitor_name'), table_name='gc_visits')
    op.drop_index(op.f('ix_gc_visits_request_id'), table_name='gc_visits')
    op.drop_index(op.f('ix_gc_visits_project_id'), table_name='gc_visits')
    op.drop_table('gc_visits')
    op.drop_index(op.f('ix_gc_report_runs_schedule_id'), table_name='gc_report_runs')
    op.drop_index(op.f('ix_gc_report_runs_project_id'), table_name='gc_report_runs')
    op.drop_table('gc_report_runs')
    op.drop_index(op.f('ix_gc_plan_shapes_zone_id'), table_name='gc_plan_shapes')
    op.drop_index(op.f('ix_gc_plan_shapes_project_id'), table_name='gc_plan_shapes')
    op.drop_index(op.f('ix_gc_plan_shapes_level'), table_name='gc_plan_shapes')
    op.drop_table('gc_plan_shapes')
    op.drop_index(op.f('ix_gc_induction_attendance_session_id'), table_name='gc_induction_attendance')
    op.drop_index(op.f('ix_gc_induction_attendance_project_id'), table_name='gc_induction_attendance')
    op.drop_table('gc_induction_attendance')
    op.drop_index(op.f('ix_gc_contractor_accounts_project_id'), table_name='gc_contractor_accounts')
    op.drop_index(op.f('ix_gc_contractor_accounts_company_id'), table_name='gc_contractor_accounts')
    op.drop_table('gc_contractor_accounts')
    op.drop_index(op.f('ix_gc_zones_zone_ref'), table_name='gc_zones')
    op.drop_index(op.f('ix_gc_zones_project_id'), table_name='gc_zones')
    op.drop_index(op.f('ix_gc_zones_parent_id'), table_name='gc_zones')
    op.drop_table('gc_zones')
    op.drop_index(op.f('ix_gc_visitor_profiles_project_id'), table_name='gc_visitor_profiles')
    op.drop_index(op.f('ix_gc_visitor_profiles_name'), table_name='gc_visitor_profiles')
    op.drop_table('gc_visitor_profiles')
    op.drop_index(op.f('ix_gc_visitor_policy_project_id'), table_name='gc_visitor_policy')
    op.drop_index(op.f('ix_gc_visitor_policy_policy_key'), table_name='gc_visitor_policy')
    op.drop_table('gc_visitor_policy')
    op.drop_index(op.f('ix_gc_visit_requests_visitor_name'), table_name='gc_visit_requests')
    op.drop_index(op.f('ix_gc_visit_requests_project_id'), table_name='gc_visit_requests')
    op.drop_table('gc_visit_requests')
    op.drop_index(op.f('ix_gc_report_schedules_project_id'), table_name='gc_report_schedules')
    op.drop_table('gc_report_schedules')
    op.drop_index(op.f('ix_gc_reference_values_list_id'), table_name='gc_reference_values')
    op.drop_table('gc_reference_values')
    op.drop_index(op.f('ix_gc_notification_channels_rule_id'), table_name='gc_notification_channels')
    op.drop_table('gc_notification_channels')
    op.drop_index(op.f('ix_gc_induction_sessions_session_ref'), table_name='gc_induction_sessions')
    op.drop_index(op.f('ix_gc_induction_sessions_project_id'), table_name='gc_induction_sessions')
    op.drop_table('gc_induction_sessions')
    op.drop_index(op.f('ix_gc_devices_project_id'), table_name='gc_devices')
    op.drop_index(op.f('ix_gc_devices_device_ref'), table_name='gc_devices')
    op.drop_table('gc_devices')
    op.drop_index(op.f('ix_gc_dashboard_tiles_project_id'), table_name='gc_dashboard_tiles')
    op.drop_table('gc_dashboard_tiles')
    op.drop_index(op.f('ix_gc_companies_project_id'), table_name='gc_companies')
    op.drop_index(op.f('ix_gc_companies_name'), table_name='gc_companies')
    op.drop_table('gc_companies')
    op.drop_index(op.f('ix_gc_audit_entries_project_id'), table_name='gc_audit_entries')
    op.drop_index(op.f('ix_gc_audit_entries_action'), table_name='gc_audit_entries')
    op.drop_table('gc_audit_entries')
    op.drop_index(op.f('ix_gc_alerts_project_id'), table_name='gc_alerts')
    op.drop_index(op.f('ix_gc_alerts_kind'), table_name='gc_alerts')
    op.drop_table('gc_alerts')
    op.drop_index(op.f('ix_gc_access_thresholds_project_id'), table_name='gc_access_thresholds')
    op.drop_table('gc_access_thresholds')
    op.drop_index(op.f('ix_gc_access_events_project_id'), table_name='gc_access_events')
    op.drop_index(op.f('ix_gc_access_events_person'), table_name='gc_access_events')
    op.drop_table('gc_access_events')
    op.drop_index(op.f('ix_gc_role_permissions_role'), table_name='gc_role_permissions')
    op.drop_index(op.f('ix_gc_role_permissions_capability'), table_name='gc_role_permissions')
    op.drop_table('gc_role_permissions')
    op.drop_index(op.f('ix_gc_reference_lists_name'), table_name='gc_reference_lists')
    op.drop_table('gc_reference_lists')
    op.drop_index(op.f('ix_gc_projects_code'), table_name='gc_projects')
    op.drop_table('gc_projects')
    op.drop_index(op.f('ix_gc_notification_rules_event'), table_name='gc_notification_rules')
    op.drop_table('gc_notification_rules')
    # ### end Alembic commands ###
